---
title: "MAD345 Mining II(T), Week 02" 
description: "Lecture: Mining Method Selection"
date: 2020-10-14T08:00:00-03:00
output:
  html_document:
    toc: true
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    code_folding: show
    number_sections: true

fontsize: 14pt
tags: [mad345_lecturenotes,mad345_lecturenotes_week02]
comments: false
---
```{r , echo=FALSE}
library(kableExtra)
text_tbl <- data.frame(
Date=c("October 7","October 8","October 14"),
Topic=c("[Introduction](/posts/071020_post01_mad345t/index.html)",
        "[Rocks, minerals and mineral inventory evaluation](/posts/081020_post01_mad345p/index.html)",
        "Mining Method Selection (Lecture slides [link](/upload/mad345t_w02_oct14.pdf))")
)

kbl(text_tbl,escape = F) %>%
    kable_styling(bootstrap_options = c("striped", "hover"), full_width = T)%>%
  column_spec(1, width = "8em")%>%
    column_spec(2, width = "40em")%>%
  row_spec(3, background = "orange", color="black", bold = TRUE)%>%
  row_spec(1:2, color="lightgrey",background = "white")

```

Dear all,

These are the videos for U/G productions.

Room-and-pillar mining: 

```{r, eval=FALSE, echo=FALSE}
<iframe width="560" height="315" src="https://www.youtube.com/embed/eBWQ6arUofs" frameborder="0" allowfullscreen></iframe>
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/eBWQ6arUofs" frameborder="0" allowfullscreen></iframe>

Longwall mining: 

```{r, eval=FALSE, echo=FALSE}
<iframe width="560" height="315" src="https://www.youtube.com/embed/1T74s7jaI-c" frameborder="0" allowfullscreen></iframe>
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/1T74s7jaI-c" frameborder="0" allowfullscreen></iframe>

Block caving: 

```{r, eval=FALSE, echo=FALSE}
<iframe width="560" height="315" src="https://www.youtube.com/embed/hYJvFm_46_E " frameborder="0" allowfullscreen></iframe>
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/hYJvFm_46_E " frameborder="0" allowfullscreen></iframe>

Sublevel caving: 

```{r, eval=FALSE, echo=FALSE}
<iframe width="560" height="315" src="https://www.youtube.com/embed/qxLFKhLjIVI" frameborder="0" allowfullscreen></iframe>
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/qxLFKhLjIVI" frameborder="0" allowfullscreen></iframe>

`r emo::ji("sun")` GERTUNC `r emo::ji("hammer_and_pick")`




